let apps=[];
const login=document.getElementById('login'),dash=document.getElementById('dash'),loginMsg=document.getElementById('loginMsg');
async function check(){const r=await fetch('/api/admin/me');if(r.ok){const j=await r.json();showDash(j.email)}else login.classList.remove('hidden')}
function showDash(email){login.classList.add('hidden');dash.classList.remove('hidden');document.getElementById('adminEmail').textContent=email;load()}
async function load(){const r=await fetch('/api/admin/applications');if(!r.ok)return location.reload();apps=(await r.json()).applications;render()}
function render(){const q=document.getElementById('search').value.toLowerCase();const filtered=apps.filter(a=>`${a.reference} ${a.name} ${a.email}`.toLowerCase().includes(q));document.getElementById('total').textContent=apps.length;document.getElementById('pending').textContent=apps.filter(a=>a.status==='Pending').length;document.getElementById('review').textContent=apps.filter(a=>a.status==='Under Review').length;document.getElementById('approved').textContent=apps.filter(a=>a.status==='Approved').length;document.getElementById('rows').innerHTML=filtered.map(a=>`<tr><td>${esc(a.reference)}</td><td>${esc(a.name)}<br><small>${esc(a.phone)}</small></td><td>${esc(a.email)}</td><td>${esc(a.state)}</td><td>${new Date(a.created_at).toLocaleDateString()}</td><td><select class="status" data-id="${a.id}">${['Pending','Under Review','Approved','Rejected'].map(s=>`<option ${s===a.status?'selected':''}>${s}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td colspan="6">No applications found.</td></tr>';document.querySelectorAll('.status').forEach(x=>x.addEventListener('change',update));}
function esc(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function update(e){const r=await fetch('/api/admin/applications/'+e.target.dataset.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:e.target.value})});if(r.ok){const j=await r.json();const a=apps.find(x=>x.id===j.application.id);if(a)a.status=j.application.status;render();}}
document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:f.get('email'),password:f.get('password')})});if(r.ok)showDash(f.get('email'));else loginMsg.textContent='Invalid login.'});
document.getElementById('logout').addEventListener('click',async()=>{await fetch('/api/admin/logout',{method:'POST'});location.reload()});document.getElementById('search').addEventListener('input',render);check();
